EasyLearning.WebUI/Areas/student/Models/Dashboard.cs
namespace EasyLearning.WebUI.Areas.student.Models
{
    public class Dashboard : lecturer.Models.Dashboard
    {
        public int NumberOfNewStudies { get; set; }
    }
}

EasyLearning.WebUI/Areas/adminsecured/Controllers/officeController.cs
using EasyLearning.Domain.Abstract.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using EasyLearning.Domain.Entity;
using System.Web;
using EasyLearning.Domain.Identity;
using PagedList;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Web.Helpers;
using EasyLearning.WebUI.Areas.adminsecured.Models;
using EasyLearning.Domain.Models;

namespace EasyLearning.WebUI.Areas.adminsecured.Controllers
{
    [Authorize(Roles = Roles.Admin)]
    public class officeController : Controller
    {
        ICollegeService _collegeService;
        IDepartmentService _departmentService;
        IStudentService _studentService;
        ICourseService _courseService;
        ILecturerService _lecturerService;
        IReplyService _replyService;
        ICommentService _commentService;
        IStudyService _studyService;

        public officeController(ICollegeService _collegeService, IDepartmentService _depertmentService,
            IStudentService _studentService, ICourseService _courseService,
            ILecturerService _lecturerService, IReplyService _replyService,
            ICommentService _commentService, IStudyService _studyService)
        {
            this._collegeService = _collegeService;
            this._departmentService = _depertmentService;
            this._studentService = _studentService;
            this._courseService = _courseService;
            this._lecturerService = _lecturerService;
            this._replyService = _replyService;
            this._commentService = _commentService;
            this._studyService = _studyService;
        }

        public ActionResult Index()
        {
            Dashboard dashboard = new Dashboard
            {
                NumberOfColleges = _collegeService.GetAll().Count(),
                NumberOfCourses = _courseService.GetAll().Count(),
                NumberOfDepartment = _departmentService.GetAll().Count(),
                NumberOfLecturers = _lecturerService.GetAll().Count(),
                NumberOfStudents = _studentService.GetAll().Count(),
                NumberOfStudies = _studyService.GetAll().Count()
            };
            return View(dashboard);
        }

        public async Task<ActionResult> profile()
        {
            AppUser user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            return View(user);
        }

        public ActionResult upload()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> upload(HttpPostedFileBase image = null)
        {
            if (VerifyImage(image))
            {
                AppUser user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    bool success = await ModifyUserImage(user.Id, image);
                    if (success)
                        return RedirectToAction("profile");
                }
            }
            return View();
        }

        public ActionResult colleges(string id, int? page)
        {
            int pageSize = 5;
            int pageNumber = page ?? 1;
            if (string.IsNullOrEmpty(id))
            {
                var colleges = _collegeService.GetAll();
                return View(colleges.ToPagedList(pageNumber, pageSize));
            }
            College college = _collegeService.GetAll().Where(x => x.Title.ToLower() == id.ToLower()).SingleOrDefault();
            if (college != null)
                return View("college", college);
            else
            {
                ModelState.Clear();
                TempData["error"] = "The college wasn't found";
                return RedirectToAction("colleges", new { id = "" });
            }
        }

        public ActionResult departments(string id, int? page)
        {
            int pageSize = 5;
            int pageNumber = page ?? 1;
            if (!string.IsNullOrEmpty(id))
            {
                var collegeDepartment = _collegeService.GetAll().Where(x => x.Title == id).SingleOrDefault();
                ViewBag.current = id;
                if (collegeDepartment != null)
                    return View(collegeDepartment.Departments.ToPagedList(pageNumber, pageSize));
                TempData["error"] = string.Format("The College: {0}, Wast found", id);
                return RedirectToAction("department", new { id = "" });
            }
            ViewBag.current = "All Colleges";
            return View(_departmentService.GetAll().ToPagedList(pageNumber, pageSize));
        }

        public ActionResult department(string departCode)
        {
            if (!string.IsNullOrEmpty(departCode))
            {
                Department model = _departmentService.GetAll().Where(x => x.Title.ToLower() == departCode.ToLower()).LastOrDefault();
                if (model != null)
                    return View(model);
            }
            TempData["error"] = "No such department was found";
            return RedirectToAction("departments");
        }

        public ActionResult students(string id, int? page)
        {
            int pageSize = 20;
            int pageNumber = page ?? 1;
            if (id == null)
            {
                ViewBag.DepartmentName = "All";
                var AllStudents = _studentService.GetAll().OrderBy(x => x.CreatedDate);
                return View(AllStudents.ToPagedList(pageNumber, pageSize));
            }
            ViewBag.DepartmentName = _departmentService.GetAll().Where(x => x.Title == id).Single().Name;
            var students = _departmentService.GetAll().First(x => x.Title == id).Students;
            return View(students.ToPagedList(pageNumber, pageSize));
        }

        [ActionName("student-courses")]
        public async Task<ActionResult> StudentCourses(string RegNo, int? page)
        {
            if (RegNo != null)
            {
                Student student = await _studentService.GetByRegNoAsync(RegNo);
                if (student != null)
                {
                    int pageSize = 12;
                    int pageNumber = page ?? 1;
                    ViewBag.Current = student.AppUser.FullName;
                    return View("courses", student.Courses.ToPagedList(pageNumber, pageSize));
                }
            }
            TempData["error"] = "No such student was found";
            return RedirectToAction("students");
        }

        public ActionResult lecturers(string id, int? page)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;
            if (string.IsNullOrEmpty(id))
            {
                ViewBag.current = "All";
                var allLecturers = _lecturerService.GetAll().OrderBy(x => x.Department.Name);
                return View(allLecturers.ToPagedList(pageNumber, pageSize));
            }
            var lecturer = _departmentService.GetAll().Where(x => x.Title.ToLower() == id.ToLower()).Single().Lecturers;
            ViewBag.current = _departmentService.GetAll().First(x => x.Title.ToLower() == id.ToLower()).Name + " Department";
            return View(lecturer.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult lecturer()
        {
            return RedirectToAction("lecturers");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> lecturer(string RegNo)
        {
            if (!string.IsNullOrEmpty(RegNo))
            {
                Lecturer lecturer = await _lecturerService.GetByRegNoAsync(RegNo);
                if (lecturer != null)
                    return View(lecturer);
            }
            TempData["error"] = "No Lecturer with such RegNo was found";
            return RedirectToAction("lecturers");
        }

        [ActionName("lecturer-courses")]
        public async Task<ActionResult> LecturerCourses(string RegNo, int? page)
        {
            Lecturer lecturer = await _lecturerService.GetByRegNoAsync(RegNo);
            if (lecturer != null)
            {
                int pageSize = 20;
                int pageNumber = page ?? 1;
                ViewBag.Current = lecturer.AppUser.FullName;
                return View("Courses", lecturer.Courses.ToPagedList(pageNumber, pageSize));
            }
            TempData["error"] = "Lecturer not found";
            return RedirectToAction("lecturers");
        }

        public ActionResult courses(string id, int? page)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;
            if (id == null)
            {
                IEnumerable<Course> AllCourses = _courseService.GetAll().OrderBy(x => x.CourseCode);
                ViewBag.courses = "active";
                ViewBag.Current = "All Courses";
                return View(AllCourses.ToPagedList(pageNumber, pageSize));
            }
            Department department = _departmentService.GetAll().First(x => x.Title == id);
            var DepartmentCourses = department.Courses.OrderBy(x => x.CourseCode);
            ViewBag.Current = department.Name;
            return View(DepartmentCourses.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult course(int id)
        {
            ViewBag.courses = "active";
            var course = _courseService.GetAll().First(x => x.ID == id);
            ViewBag.DepartmentCode = course.DepartmentCode;
            return View(course);
        }

        [ActionName("add-course")]
        public ActionResult AddCourse()
        {
            ViewBag.courses = "active";
            PopulateDepartmentDropDownList();
            return View("AddCourse", new AddCourseViewModel());
        }

        [ActionName("add-course")]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> AddCourse(AddCourseViewModel model)
        {

EasyLearning.WebUI/Areas/lecturer/Views/office/AddStudy.cshtml
@model EasyLearning.Domain.Entity.Study

@{
    ViewBag.Title = "Add Study";
}

<section class="content-header">
    <h1>
        Add study for @ViewBag.Current
    </h1>
</section>


<section class="content">
    @using (Html.BeginForm("AddStudy", "office", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(x => x.CourseID)
        @Html.AntiForgeryToken()
        
        <div class="row">
            <div class="col-md-offset-3 col-md-6 col-sm-12">
                <dic class="box">
                    <div class="box-header">
                        <h3 class="box-title">Add study</h3>
                    </div>
                    <div class="box-body">
                        @if (TempData["error"] != null)
                        {
                            <div class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                                @TempData["error"]
                            </div>
                        }
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group has-feedback">
                            @Html.LabelFor(model => model.Name)
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            <span class="glyphicon glyphicon-align-justify form-control-feedback"></span>
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group has-feedback">
                            @Html.LabelFor(model => model.Summary)
                            @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control", rows = 7} })
                            @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group has-feedback">
                            @Html.LabelFor(x => x.DeadLine)
                            @Html.EditorFor(x => x.DeadLine, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(x => x.DeadLine, "", new { @class = "text-danger"})
                        </div>

                        <div class="form-group">
                            @Html.Label("Video File")
                            <input type="file" id="video" name="video" class="form-control">
                            <p class="help-block">Any  Video file format. Max: 100 MB</p>
                        </div>

                        <div class="form-group">
                            @Html.Label("Material")
                            <input type="file" id="material" name="material" class="form-control">
                            <p class="help-block">Either PDF or Word doc. Should also include assignment if any.</p>
                        </div>
                        <button class="btn btn-flat btn-success" type="submit">Save Study</button>
                    </div>
                </dic>
            </div>
        </div>
    }
</section>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EasyLearning.WebUI/Areas/lecturer/Views/office/Assignments.cshtml
@using EasyLearning.Domain.Entity;
@model List<Assignment>

@{
    ViewBag.Title = "Assignments";
    int count = 0;
}

<section class="content-header">
    <h1>
        Submitted Assignments
    </h1>
    <h3 class="pull-right">
        <a href="@Url.Action("study", new { id = ViewBag.StudyID })" class="btn btn-flat btn-warning">Return to Study</a>
    </h3>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="box">
                <div class="box-body">
                    <table class="table table-hover table-responsive table-striped">
                        @if (Model.Count == 0)
                        {
                            <tr><td colspan="2">No Assignment submitted for this study Yet</td></tr>
                        }
                        else
                        {
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Reg No</th>
                                    <th>Department</th>
                                    <th>Score</th>
                                    <th>Time</th>
                                    <th>view</th>                                                                       
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var assign in Model)
                                {
                                    <tr>
                                        <td>@(++count)</td>
                                        <td>@Html.DisplayFor(x => assign.Student.AppUser.FullName)</td>
                                        <td>@Html.DisplayFor(x => assign.StudentRegNo)</td>
                                        <td>@Html.DisplayFor(x => assign.Student.Department.Name)</td>                                       
                                        <td>@Html.DisplayFor(x => assign.Score)</td>
                                        <td>@Html.DisplayFor(x => assign.CreatedDate)</td>
                                        <td><a href="@Url.Action("view", new { id = assign.ID })">View / Grade</a></td>
                                    </tr>
                                }
                            </tbody>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

EasyLearning.WebUI/Areas/lecturer/Views/office/Index.cshtml
@model EasyLearning.WebUI.Areas.lecturer.Models.Dashboard

@{
    ViewBag.Title = "Index";
}


<div>
    <section class="content-header">
        <h1>
            Dashboard
            <small>Welcome</small>
        </h1>

    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="info-box">
                    <span class="info-box-icon bg-green"><i class="ion ion-stats-bars"></i></span>
                    <div class="info-box-content">
                        <span class="info-box-text"><a href="@Url.Action("courses")">Courses</a></span>
                        <span class="info-box-number">@Model.NumberOfCourses</span>
                    </div><!-- /.info-box-content -->
                </div><!-- /.info-box -->
            </div>

            <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="info-box">
                    <span class="info-box-icon bg-red"><i class="ion ion-ios-home"></i></span>
                    <div class="info-box-content">
                        <span class="info-box-text"><a href="@Url.Action("studies")">Studies</a></span>
                        <span class="info-box-number">@Model.NumberOfStudies</span>
                    </div>
                </div>
            </div>
            <!-- fix for small devices only -->
            <div class="clearfix visible-sm-block"></div>

            <!-- /.col -->
            <!-- /.col -->
        </div>

    </section><!-- /.content -->

</div>

EasyLearning.WebUI/Areas/lecturer/Views/office/Studies.cshtml
@using EasyLearning.Domain.Entity
@using PagedList
@using PagedList.Mvc
@model IPagedList<Study>

@{
    ViewBag.Title = "Studies";
}


<section class="content-header">
    <h1>
        @ViewBag.Current
        <small> Studies</small>
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Studies</h3>
                    @if (ViewBag.CourseID != null)
                    {
                        <h5 class="pull-right"><a href="@Url.Action("AddStudy", new { id = ViewBag.CourseID })">Add new</a></h5>
                    }
                </div>

                <div class="box-body no-padding">
                    @if (Model.Count() == 0)
                    {
                        <span class="pad">No Study added yet</span>
                    }
                    else
                    {
                        int courseCount = 0;
                        <table class="table table-hover table-responsive">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Title</th>
                                    <th>Course Code</th>
                                    <th>Date</th>
                                    <th>Lecturer</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var study in Model)
                                {
                                    <tr>
                                        <td> @(++courseCount)</td>
                                        <td> <a href="@Url.Action("study", new { id = study.ID })" class="btn btn-default">@Html.DisplayFor(x => study.Name)</a></td>
                                        <td>@study.Course.CourseCode</td>
                                        <td>@Html.DisplayFor(x => study.CreatedDate)</td>
                                        <td>@Html.GetFullName(study.CreatedBy)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="pad">
                            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                            @Html.PagedListPager(Model, page => Url.Action("studies", new { page }))
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</section>
@section Styles{
    <link rel="stylesheet" href="~/Content/PagedList.css" />
}

EasyLearning.WebUI/Areas/lecturer/Views/office/comments.cshtml
@model IEnumerable<EasyLearning.Domain.Entity.Comment>

@if (Model.Count() == 0)
{
    <div class="pad">
        <p class="h2">No Comments Yet</p>
    </div>
}
else
{
    foreach (var comment in Model)
    {
        <div class="direct-chat-msg">
            <div class="direct-chat-info clearfix">
                <span class="direct-chat-name pull-left">@Html.GetFullName(comment.CreatedBy)</span>
                <span class="direct-chat-timestamp pull-right">@comment.CreatedDate.Date</span>
            </div><!-- /.direct-chat-info -->
            <img class="direct-chat-img" src="@Url.Action("CommentImage", new { username = comment.CreatedBy })" alt="message user image"><!-- /.direct-chat-img -->
            <div class="direct-chat-text">
                @comment.Content @*<p><a id="reply"><i class="fa fa-reply"></i></a></p>*@
            </div><!-- /.direct-chat-text -->
        </div>
    }
}

EasyLearning.WebUI/Areas/lecturer/Views/office/course.cshtml
@using EasyLearning.Domain.Entity;
@model Course

@{
    ViewBag.Title = "course";
}

<div>
    <section class="content-header">
        <h1>
            @Model.CourseTitle
        </h1>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-sm-6 col-md-6">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Course Information</h3>
                        <span class="pull-right">
                            <a href="@Url.Action("AddStudy", new { id = Model.ID })" class="btn btn-flat btn-info">Add New Study</a>
                        </span>
                    </div>
                    <div class="box-body pad">
                        <p>
                            Name: @Model.CourseTitle
                        </p>
                        <p>
                            Code: @Model.CourseCode
                        </p>
                        <p>
                            Unit: @Model.CreditLoad
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Lecturers Teaching this Course</h3>
                        <span class="pull-right">
                            <a class="btn btn-flat btn-info" href="@Url.Action("students", new { course = Model.CourseCode })">Students for this Course</a>
                        </span>
                    </div>
                    <div class="box-body">
                        @foreach (var lect in Model.Lecturers)
                        {
                            <p class="pad">
                                @lect.AppUser.FullName
                            </p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

EasyLearning.WebUI/Areas/lecturer/Views/office/courses.cshtml
@using EasyLearning.Domain.Entity;
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<Course>

@{
    ViewBag.Title = "courses";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Current Courses
        <small> Courses</small>
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Courses</h3>
                </div>

                <div class="box-body no-padding">
                    @if (Model.Count() == 0)
                    {
                        <span class="pad">No Course added</span>
                    }
                    else
                    {
                        int courseCount = 0;
                        <table class="table table-hover table-responsive">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Title</th>
                                    <th>Course Code</th>
                                    <th>Unit</th>
                                    <th>Studies</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var course in Model)
                                {
                                    <tr>
                                        <td> @(++courseCount)</td>
                                        <td> <a href="@Url.Action("course", new { id = course.ID })" class="btn btn-default">@Html.DisplayFor(x => course.CourseTitle)</a></td>
                                        <td> @Html.DisplayFor(x => course.CourseCode)</td>
                                        <th>@Html.DisplayFor(x => course.CreditLoad)</th>
                                        <td><a class="btn btn-flat btn-info" href="@Url.Action("studies", new { id = course.ID })">View</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="pad">
                            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                            @Html.PagedListPager(Model, page => Url.Action("departments", new { page }))
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</section>
@section Styles{
    <link rel="stylesheet" href="~/Content/PagedList.css" />
}

EasyLearning.WebUI/Areas/lecturer/Views/office/study.cshtml
@using EasyLearning.Domain.Entity;
@model Study

@{
    ViewBag.Title = "study";
    AjaxOptions ajaxOpts = new AjaxOptions
    {
        OnSuccess = "Completed",
        UpdateTargetId = "CommentBody",
        Url = Url.Action("AddComment"),
        HttpMethod = "POST",
    };
}

<section class="content-header">
    <h1>
        @Model.Name
    </h1>

</section>
<section class="content">
    <div class="row">
        <div class="jumbotron pad">
            <p class="text-danger">
                @Model.Summary
            </p>
            @if (Model.VideoName != null)
            {
                <p>
                    <video controls="controls">
                        <source src="@Url.Action("Video", new { id = Model.ID })" type="@Model.VideoType" />
                    </video>
                </p>
                <a class="btn btn-flat btn-primary" href="@Url.Action("Video", new { id = Model.ID })"><i class="fa fa-file-video-o fa-fw"></i>Download Video</a>
            }
            @if (Model.NoteName != null)
            {
                <a class="btn btn-flat btn-info" href="@Url.Action("Note", new { id = Model.ID })"><i class="fa fa-book fa-fw"></i>Download Note</a>
                <a class="btn btn-flat btn-success" href="@Url.Action("assignments", new{id = Model.ID})"><i class="fa fa-list fa-fw"></i>Assignments</a>
            }

        </div>
        <div class="col-md-offset-2 col-sm-offset-2 col-sm-8 col-md-8">
            <!-- DIRECT CHAT SUCCESS -->
            <div class="box box-info direct-chat direct-chat-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Comments Box</h3>

                </div><!-- /.box-header -->
                <div class="box-body">
                    <!-- Conversations are loaded here -->
                    <div class="direct-chat-messages" id="CommentBody">
                        @Html.Partial("comments", Model.Comments)
                    </div><!--/.direct-chat-messages-->
                    <!-- Contacts are loaded here -->
                    <!-- /.direct-chat-pane -->
                </div><!-- /.box-body -->
                <div class="box-footer">
                    @*@using (Html.BeginForm("AddComment", "office", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("StudyID", Model.ID)
                            <div class="input-group">
                                <input type="text" name="Content" id="Content" placeholder="Type Message ..." class="form-control">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-success btn-flat">Send</button>
                                </span>
                            </div>
                        }*@

                    @using (Ajax.BeginForm(ajaxOpts))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("StudyID", Model.ID)
                        <div class="input-group">
                            <input type="text" name="Content" id="Content" placeholder="Type Message ..." class="form-control">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-success btn-flat">Send</button>
                            </span>
                        </div>
                    }

                </div><!-- /.box-footer-->
            </div><!--/.direct-chat -->
        </div>
    </div>
</section>

@section scripts{
    @Scripts.Render("~/bundles/ajax")
    <script>
        function Completed(data) {
            $('#Content').val("");
        }
    </script>
}